<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LT075810" ignored="0" name="Driver Automaton Assessment" tests="2" failures="1" timestamp="2020-05-17T18:11:44 CAT" time="88.452" errors="0">
  <testcase name="ValidateUploadErrorMessage" time="37.881" classname="com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg"/>
  <testcase name="ValidateUploadErrorMessage" time="43.282" classname="com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.iLab.testCases.TC_ApplyOnline_ValidateUploadErrorMsg.ValidateUploadErrorMessage(TC_ApplyOnline_ValidateUploadErrorMsg.java:182)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- ValidateUploadErrorMessage -->
</testsuite> <!-- Driver Automaton Assessment -->
